name: "[Push] Build dev"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: get current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: set version with current date
        id: versioning
        run: |
          echo "VERSION=${{ env.TIME }}" >> $GITHUB_OUTPUT
          echo "::set-output name=VERSION::${{ env.TIME }}"

  docker:
      if: github.repository_owner == 'ampmjbnu'
      needs: versioning
      runs-on: ubuntu-latest
      env:
        VERSION: ${{ needs.versioning.outputs.version }}
      steps:
        - uses: actions/checkout@v2
        - name: get service name
          run: |
            echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

        - name: Upload docker
          uses: docker/build-push-action@v1
          with:
            path: .
            repository: kiku99/${{ env.SERVICE }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: ${{ env.VERSION }}
